# Example only: set these locally; never commit private configuration.
export IOH_PROJECT_ROOT="REQUIRED_LOCAL_SOURCE_PROJECT"
export IOH_QC_OUTPUT_ROOT="REQUIRED_LOCAL_QC_WORKSPACE"
export IOH_STARTUP_AUDIT_ROOT="REQUIRED_LOCAL_STARTUP_AUDIT"
export IOH_VITALDB_RAW_ROOT="REQUIRED_LOCAL_VITALDB_ROOT_WITH_TRKS_CSV"
export IOH_VITALDB_TRACK_DIRS="REQUIRED_LOCAL_TRACK_DIRECTORIES_SEPARATED_BY_OS_PATHSEP"
export IOH_VITALDB_LABS="REQUIRED_LOCAL_OFFICIAL_LABS_CSV"
# Required only for the observation-packaging script, not statistical reruns:
# export IOH_IMAGE_REVIEW_INPUT_JSON="PRIVATE_PRIOR_REVIEW_OBSERVATIONS_JSON"
# Optional when dependencies are installed outside the active environment:
# export IOH_QC_DEPENDENCIES="LOCAL_PYTHON_DEPENDENCIES"
# export CODEX_NODE_MODULES="LOCAL_NODE_DEPENDENCIES"
